#!/usr/bin/env php
<?php
// application.php

require __DIR__.'/vendor/autoload.php';

use FastVolt\Utils\Console\Terminal;
use FastVolt\Utils\Console\TestCommands\Greetings;

$all_commands = [

    'FastVolt\\Utils\\Console\\TestCommands\\Greetings'
];

$terminal = Terminal::new('FastVolt Terminal', 1.2) 
-> commands($all_commands)
-> save_deploy();
